title: 我的博客
subtitle: 我是谁，我要到哪里去
meta: 
  description: 这是我的博客
  keywords: 写作，思考，生活
  author: zhangxiaoyang
profile:
  avatar: https://avatars2.githubusercontent.com/u/2735163
navigation:
  - name: index
    icon: fa-home
    color: 3369e8
  - name: archive
    icon: fa-archive
    color: 3369e8
  - name: category
    icon: fa-th-large
    color: 3369e8
  - name: tag
    icon: fa-tag
    color: 3369e8
site:
  url: github.com/zhangxiaoyang
  theme: default
  banner: http://ww3.sinaimg.cn/large/659dc7b4jw1epba3z4g6rj20m80dw77t.jpg
  copyright: © 2020 zhangxiaoyang
